//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spinecases2.FTSEmailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailMsgRequestDto", Namespace="http://schemas.datacontract.org/2004/07/TbEmailService.Dtos")]
    [System.SerializableAttribute()]
    public partial class SendEmailMsgRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Bcc {
            get {
                return this.BccField;
            }
            set {
                if ((object.ReferenceEquals(this.BccField, value) != true)) {
                    this.BccField = value;
                    this.RaisePropertyChanged("Bcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Cc {
            get {
                return this.CcField;
            }
            set {
                if ((object.ReferenceEquals(this.CcField, value) != true)) {
                    this.CcField = value;
                    this.RaisePropertyChanged("Cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDisplayName {
            get {
                return this.FromDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromDisplayNameField, value) != true)) {
                    this.FromDisplayNameField = value;
                    this.RaisePropertyChanged("FromDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBodyHtml {
            get {
                return this.IsBodyHtmlField;
            }
            set {
                if ((this.IsBodyHtmlField.Equals(value) != true)) {
                    this.IsBodyHtmlField = value;
                    this.RaisePropertyChanged("IsBodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainHeader {
            get {
                return this.MainHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.MainHeaderField, value) != true)) {
                    this.MainHeaderField = value;
                    this.RaisePropertyChanged("MainHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubHeader {
            get {
                return this.SubHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.SubHeaderField, value) != true)) {
                    this.SubHeaderField = value;
                    this.RaisePropertyChanged("SubHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailMsgRequestDto.EmailType", Namespace="http://schemas.datacontract.org/2004/07/TbEmailService.Dtos")]
        public enum EmailType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Promo = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CustomerAppreciation = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            None = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ClientBirthday = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PassengerBirthday = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailMsgReplyDto", Namespace="http://schemas.datacontract.org/2004/07/TbEmailService.Dtos")]
    [System.SerializableAttribute()]
    public partial class SendEmailMsgReplyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private spinecases2.FTSEmailService.ErrorMessageDto ErrorMessageDtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private spinecases2.FTSEmailService.SendEmailMsgRequestDto SendEmailMsgRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public spinecases2.FTSEmailService.ErrorMessageDto ErrorMessageDto {
            get {
                return this.ErrorMessageDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageDtoField, value) != true)) {
                    this.ErrorMessageDtoField = value;
                    this.RaisePropertyChanged("ErrorMessageDto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public spinecases2.FTSEmailService.SendEmailMsgRequestDto SendEmailMsgRequest {
            get {
                return this.SendEmailMsgRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.SendEmailMsgRequestField, value) != true)) {
                    this.SendEmailMsgRequestField = value;
                    this.RaisePropertyChanged("SendEmailMsgRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorMessageDto", Namespace="http://schemas.datacontract.org/2004/07/TbEmailService.Dtos")]
    [System.SerializableAttribute()]
    public partial class ErrorMessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessageTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessageText {
            get {
                return this.ErrorMessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageTextField, value) != true)) {
                    this.ErrorMessageTextField = value;
                    this.RaisePropertyChanged("ErrorMessageText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTSEmailService.ITbEmailService")]
    public interface ITbEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITbEmailService/SendEmail", ReplyAction="http://tempuri.org/ITbEmailService/SendEmailResponse")]
        spinecases2.FTSEmailService.SendEmailMsgReplyDto SendEmail(spinecases2.FTSEmailService.SendEmailMsgRequestDto.EmailType emailType, spinecases2.FTSEmailService.SendEmailMsgRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITbEmailService/SendEmail", ReplyAction="http://tempuri.org/ITbEmailService/SendEmailResponse")]
        System.Threading.Tasks.Task<spinecases2.FTSEmailService.SendEmailMsgReplyDto> SendEmailAsync(spinecases2.FTSEmailService.SendEmailMsgRequestDto.EmailType emailType, spinecases2.FTSEmailService.SendEmailMsgRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITbEmailServiceChannel : spinecases2.FTSEmailService.ITbEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TbEmailServiceClient : System.ServiceModel.ClientBase<spinecases2.FTSEmailService.ITbEmailService>, spinecases2.FTSEmailService.ITbEmailService {
        
        public TbEmailServiceClient() {
        }
        
        public TbEmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TbEmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TbEmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TbEmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public spinecases2.FTSEmailService.SendEmailMsgReplyDto SendEmail(spinecases2.FTSEmailService.SendEmailMsgRequestDto.EmailType emailType, spinecases2.FTSEmailService.SendEmailMsgRequestDto request) {
            return base.Channel.SendEmail(emailType, request);
        }
        
        public System.Threading.Tasks.Task<spinecases2.FTSEmailService.SendEmailMsgReplyDto> SendEmailAsync(spinecases2.FTSEmailService.SendEmailMsgRequestDto.EmailType emailType, spinecases2.FTSEmailService.SendEmailMsgRequestDto request) {
            return base.Channel.SendEmailAsync(emailType, request);
        }
    }
}
